name: generate_readthedocs

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - review_requested

permissions:
  pull-requests: write

jobs:
  pull-request-links:
    runs-on: ubuntu-22.04
    steps:
      - uses: hkabbech/TrackSegNet/readthedocs-preview@dev
        with:
          project-slug: "tracksegnet"
