name: "Check code with pylint"

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analyzing the code with pylint
      run: |
        pylint --max-line-length=120 --fail-under=8 --ignored-modules=tensorflow.* --output-format=colorized $(git ls-files '*.py')
        # ignored-modules=tensorflow.*: https://github.com/pylint-dev/pylint/issues/2603
