name: "ReadtheDocs Pull Request Preview"

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - review_requested

permissions:
  pull-requests: write

jobs:
  pull-request-links:
    runs-on: ubuntu-22.04
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "tracksegnet"
